//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace ChimeraVirtualAds.Internal
{
	public interface IAdInstanceClient
	{
		void UpdateVisibilityMetric(float cameraLookAtX, float cameraLookAtY, float cameraLookAtZ, float cameraX, float cameraY, float cameraZ, float adObjectX, float adObjectY, float adObjectZ);
		void MarkInstanceDisplayed ();
	}
}