//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using co.chimeralabs.ads.managed;
using ChimeraVirtualAds.Internal;

namespace ChimeraVirtualAds.Implementation.Managed
{
	public class AdInstanceClient:IAdInstanceClient
	{
		private AdInstance adInstance;

		public AdInstanceClient (AdInstance instance)
		{
			this.adInstance = instance;
		}

		public void UpdateVisibilityMetric(float cameraLookAtX, float cameraLookAtY, float cameraLookAtZ, float cameraX, float cameraY, float cameraZ, float adObjectX, float adObjectY, float adObjectZ){
			adInstance.UpdateVisibilityMetric (cameraLookAtX, cameraLookAtY, cameraLookAtZ, cameraX, cameraY, cameraZ, adObjectX, adObjectY, adObjectZ);
		}

		public void MarkInstanceDisplayed (){
			this.adInstance.MarkInstanceDisplayedTrue();
		}
	}
}

