//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.VR;
using ChimeraVirtualAds.Internal;

namespace ChimeraVirtualAds.API
{
	public class AdInstance
	{
		private IAdInstanceClient instanceClient;
		private String instanceId;
		private String adId;
		private GameObject adObject;
		private Camera camera;
		private Boolean isInstanceDisplayed = false;

		public AdInstance (String adId, String instanceId, GameObject adObject, Camera camera, IAdInstanceClient instanceClient)
		{
			this.adId = adId;
			this.instanceId = instanceId;
			this.adObject = adObject;
			this.camera = camera;
			this.instanceClient = instanceClient;
		}
		public void UpdateVisibilityMetric(){
			Vector3 cameraLookAt = camera.transform.forward.normalized;
			Vector3 cameraPosition = camera.transform.position;
			Vector3 adObjectPosition = adObject.transform.position;
			this.instanceClient.UpdateVisibilityMetric (cameraLookAt.x, cameraLookAt.y, cameraLookAt.z, cameraPosition.x, cameraPosition.y, cameraPosition.z, adObjectPosition.x, adObjectPosition.y, adObjectPosition.z);
		}
		public void SetInstanceDisplayedTrue(){
			isInstanceDisplayed = true;
			instanceClient.MarkInstanceDisplayed ();
		}
		public Boolean IsInstanceDisplayed(){
			return isInstanceDisplayed;
		}
		public String GetInstanceId(){
			return this.instanceId;
		}
		public String GetAdId(){
			return this.adId;
		}
		public GameObject GetAdObject(){
			return this.adObject;
		}
	}
}

