//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using ChimeraVirtualAds.API;
using UnityEngine;
using UnityEngine.VR;

namespace ChimeraVirtualAds
{
	public static class AdManager
	{
		private static Hashtable imageTextureAds = new Hashtable();
		private static bool isUpdateRequired = true;
		public static void AddImageTextureAd(ImageTextureAd imageTextureAd){
			imageTextureAds.Add (imageTextureAd.GetAdId(), imageTextureAd);
			isUpdateRequired = true;
		}

		public static ImageTextureAd GetImageTextureAd(String adId){
			return (ImageTextureAd)imageTextureAds [adId];
		}

		public static void Update(AdInstance instance) {
			ImageTextureAd ad = GetImageTextureAd (instance.GetAdId ());
			if (!ad.IsTextureGenerated ()) {
				ad.GenerateTexture();
				ad.DisplayTexture();
			}
			if (instance.IsInstanceDisplayed ()) {
				instance.UpdateVisibilityMetric ();
			}
		}
	}
}

