//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using co.chimeralabs.ads.managed;

namespace ChimeraVirtualAds
{
	public class AdObjectUnity : IAdObject
	{
		private Camera camera;
		private GameObject adObject;
		Vector3 cameraLookAt;
		Vector3 cameraPosition;
		Vector3 adObjectPosition;
		public AdObjectUnity (GameObject adObject, Camera camera)
		{
			this.adObject = adObject;
			this.camera = camera;
		}
		public GameObject GetAdObject(){
			return this.adObject;
		}
		public Camera GetCamera(){
			return this.camera;
		}
		public void Update()
		{
			cameraLookAt = camera.transform.forward.normalized;
			cameraPosition = camera.transform.position;
			adObjectPosition = adObject.transform.position;
		}
		public float AdObjectX()
		{
			return adObjectPosition.x;
		}
		public float AdObjectY()
		{
			return adObjectPosition.y;
		}
		public float AdObjectZ()
		{
			return adObjectPosition.z;
		}
		public float CameraX()
		{
			return cameraPosition.x;
		}
		public float CameraY()
		{
			return cameraPosition.y;
		}
		public float CameraZ()
		{
			return cameraPosition.z;
		}
		public float CameraLA_X()
		{
			return cameraLookAt.x;
		}
		public float CameraLA_Y()
		{
			return cameraLookAt.y;
		}
		public float CameraLA_Z()
		{
			return cameraLookAt.z;
		}
	}
}

